# Spring Actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

# Spring Configuration
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    password: P@ssw0rd
    username: guilherme
    url: jdbc:mysql://localhost:3306/school
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/keycloak
          jwk-set-uri: http://localhost:8080/realms/keycloak/protocol/openid-connect/certs

# Server information
info:
  app:
    name: '@project.name@'
    version: '@project.version@'
server:
  servlet:
    context-path: /api/
  port: 8090