management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  datasource:
    password: ${SCHOOL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SCHOOL_DB_USERNAME}
    url: ${SCHOOL_DB_URL}
info:
  app:
    name: '@project.name@'
    version: '@project.version@'
server:
  servlet:
    context-path: /school/api/

# To execute
# java -jar -Dspring.config.location=classpath:application-prod.yml -DSCHOOL_DB_URL=jdbc:mysql://localhost:3306/school -DSCHOOL_DB_USERNAME=root -DSCHOOL_DB_PASSWORD=root -DFORUM_JWT_SECRET=123456